/**
 * Created by dmitrypoddubniy on 04.03.17.
 */

export const SET_ACTIVE_SERVICE = 'SET_ACTIVE_SERVICE';
export const RESET_ACTIVE_SERVICE = 'RESET_ACTIVE_SERVICE';
export const SETUP_SERVICES = 'SETUP_SERVICES';
export const FILTER_SERVICES_BY_NAME = 'FILTER_SERVICES_BY_NAME';
export const ADD_SERVICE = 'ADD_SERVICE';
export const SET_LOADER_STATE = 'SET_LOADER_STATE';
