/**
 * Created by dmitrypoddubniy on 04.03.17.
 */

export const SET_ACTIVE_SERVICE = 'SET_ACTIVE_SERVICE';
export const RESET_ACTIVE_SERVICE = 'RESET_ACTIVE_SERVICE';
export const SETUP_SERVICES = 'SETUP_SERVICES';
export const FILTER_SERVICES_BY_ID = 'FILTER_SERVICES_BY_ID';
export const FILTER_SERVICES_BY_NAME = 'FILTER_SERVICES_BY_NAME';
export const UPDATE_SERVICE_OPTIONS_BY_ID = 'UPDATE_SERVICE_OPTIONS_BY_ID';
